spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/daydayup
  mvc:
    view:
      prefix: /
      suffix: .html
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl